apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: deploy-cs_degree_planner
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - run-prod.yaml
deploy:
  cloudrun: {}