steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
            'us-central1-docker.pkg.dev/${PROJECT_ID}/jeanz-repo/jeanz-image',
            '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
            'us-central1-docker.pkg.dev/${PROJECT_ID}/jeanz-repo/jeanz-image']