# Generated by Django 4.2 on 2023-05-25 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecast', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=0)),
                ('major_credits', models.IntegerField(default=0)),
                ('bs_credits', models.IntegerField(default=0)),
                ('aoi_credits', models.IntegerField(default=0)),
                ('cultural_credits', models.IntegerField(default=0)),
                ('courses_taken', models.ManyToManyField(to='forecast.course')),
                ('interests', models.ManyToManyField(to='forecast.keyword')),
                ('major', models.ManyToManyField(to='forecast.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_in_fc', models.ManyToManyField(to='forecast.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
