# Generated by Django 4.2.1 on 2023-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aal_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gp_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sci_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ssci_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='us_credits',
            field=models.IntegerField(default=0),
        ),
    ]
