# Generated by Django 4.2 on 2023-05-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_delete_forecast'),
        ('users', '0002_profile_courses_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='forecast.keyword'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.ManyToManyField(to='forecast.major'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_in_fc', models.ManyToManyField(to='forecast.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
