# Generated by Django 4.2 on 2023-05-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_interests_profile_major_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aoi_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bs_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cultural_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='major_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
    ]
