# Generated by Django 4.2 on 2023-05-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_name', models.CharField(max_length=100)),
                ('kw_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall', models.BooleanField(default=False)),
                ('winter', models.BooleanField(default=False)),
                ('spring', models.BooleanField(default=False)),
                ('summer', models.BooleanField(default=False)),
                ('every_year', models.BooleanField(default=False)),
                ('every_year_odd', models.BooleanField(default=False)),
                ('every_year_even', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forecast.course')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=100)),
                ('major_desc', models.CharField(max_length=512)),
                ('is_minor', models.BooleanField(default=False)),
                ('has_course', models.ManyToManyField(to='forecast.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='has_kw',
            field=models.ManyToManyField(to='forecast.keyword'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_prereq',
            field=models.ManyToManyField(to='forecast.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_prereq_for',
            field=models.ManyToManyField(to='forecast.course'),
        ),
    ]
