# Generated by Django 4.2.1 on 2023-06-02 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=10)),
                ('number', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
                ('fall', models.BooleanField(default=False)),
                ('winter', models.BooleanField(default=False)),
                ('spring', models.BooleanField(default=False)),
                ('summer', models.BooleanField(default=False)),
                ('every_year', models.BooleanField(default=False)),
                ('every_year_odd', models.BooleanField(default=False)),
                ('every_year_even', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=512)),
                ('is_minor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Major_Has_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.major')),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='courses',
            field=models.ManyToManyField(through='forecast.Major_Has_Course', to='forecast.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_kw',
            field=models.ManyToManyField(to='forecast.keyword'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_prereq',
            field=models.ManyToManyField(to='forecast.course'),
        ),
    ]
