# Generated by Django 4.2 on 2023-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
    ]
