# Generated by Django 4.2 on 2023-05-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_delete_forecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='kw_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='kw_name',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='major_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='major_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='major',
            name='subject',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
